# Numpy_Assignment_2::

## Question:1

### Convert a 1D array to a 2D array with 2 rows?

#### Desired output::

array([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [2]:
import numpy as np
arr=np.array([0,1,2,3,4,5,6,7,8,9])
arr2=np.reshape(arr,(2,5))
arr2

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

## Question:2

###  How to stack two arrays vertically?

#### Desired Output::

In [13]:
x=[[0,1,2,3,4],[5,6,7,8,9]]
y=[[1,1,1,1,1],[1,1,1,1,1]]
arrX=np.array(x)
arrY=np.array(y)
arrZ=np.vstack((arrX,arrY))
arrZ


array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

## Question:3

### How to stack two arrays horizontally?

#### Desired Output::

In [20]:
    arr=[[0,1,2,3,4,1,1,1,1,1],[5,6,7,8,9,1,1,1,1,1]]
arrX=np.array(arr)

arrZ=np.split(arrX,(9,-1))
arrZ

[array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
        [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]]),
 array([], shape=(0, 10), dtype=int32),
 array([[5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])]

## Question:4

### How to convert an array of arrays into a flat 1d array?

#### Desired Output::

In [22]:
x=[[0,1,2,3,4],[5,6,7,8,9]]
arr=np.array(x)
arr.flatten()

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## Question:5

### How to Convert higher dimension into one dimension?

#### Desired Output::

In [29]:
l=[ 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14]
arr2=np.array(l)
arrhi=np.reshape(arr2,(3,5))
arr1d=arrhi.flatten()
arr1d

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

## Question:6

### Convert one dimension to higher dimension?

#### Desired Output::

In [34]:
arr=np.arange(0,15)
np.reshape(arr,(5,3))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

## Question:7

### Create 5x5 an array and find the square of an array?

In [28]:
arr=np.arange(1,26)
arr2=np.reshape(arr,(5,5))
np.square(arr2)

array([[  1,   4,   9,  16,  25],
       [ 36,  49,  64,  81, 100],
       [121, 144, 169, 196, 225],
       [256, 289, 324, 361, 400],
       [441, 484, 529, 576, 625]], dtype=int32)

## Question:8

### Create 5x6 an array and find the mean?

In [31]:
arr=np.arange(1,31)
arr2=np.reshape(arr,(5,6))
np.mean(arr2)

15.5

## Question:9

### Find the standard deviation of the previous array in Q8?

In [35]:
np.std(arr2)

8.65544144839919

## Question:10

### Find the median of the previous array in Q8?

In [36]:
np.median(arr2)

15.5

## Question:11

### Find the transpose of the previous array in Q8?

In [37]:
arr2.transpose()

array([[ 1,  7, 13, 19, 25],
       [ 2,  8, 14, 20, 26],
       [ 3,  9, 15, 21, 27],
       [ 4, 10, 16, 22, 28],
       [ 5, 11, 17, 23, 29],
       [ 6, 12, 18, 24, 30]])

## Question:12

### Create a 4x4 an array and find the sum of diagonal elements?

In [18]:
arr=np.arange(1,17)
reArr=np.reshape(arr,(4,4))
diaSum=np.trace(reArr)
diaSum

34

## Question:13

### Find the determinant of the previous array in Q12?

In [17]:
arr=np.arange(1,17)
reArr=np.reshape(arr,(4,4))
deter=np.linalg.det(reArr)
deter

4.7331654313261276e-30

## Question:14

### Find the 5th and 95th percentile of an array?

In [23]:
arr=np.arange(4,16)
percenArr5=np.percentile(arr,5)
percenArr95=np.percentile(arr,95)


## Question:15

### How to find if a given array has any null values?

In [3]:
x=[True,False,False]
np.array(x)
np.any(x)

True